spring.application.name=inventario-backend

# Puerto del servidor
server.port=8080

# Conexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/inventario_microempresa
spring.datasource.username=postgres
spring.datasource.password=kaneki979

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://ep-silent-butterfly-aq2jxtfb-pooler.c-8.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_69UkMnQhdpgz&sslmode=require&channelBinding=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080